version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - ./database:/data
    command: redis-server 
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    hostname: redisinsight
    ports:
      - 8001:8001
    environment:
      - REDIS_URI=redis://redis:6379
      - REDIS_PASSWORD=redis
